name: CI/CD

on:
  push:
    branches: 
      - master
    paths-ignore:
      - "docs/**"
      - "*.md"
  pull_request:
    branches: 
      - master
    paths-ignore:
      - "docs/**"
      - "*.md"

permissions:
  contents: write

jobs:
  run-vitest:
    name: Unit Tests (vitest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm coverage

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: coverage
          path: coverage/

  run-playwright:
    name: Integration Tests (playwright)
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm dlx playwright install --with-deps
      
      - name: Run Playwright tests
        run: pnpm dlx playwright test
      
      - name: Save report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs:
      - run-vitest
      - run-playwright
    steps:
      steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies and build
        run: |
          pnpm install
          pnpm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist